---
kind: pipeline
type: docker
name: check-all

trigger:
  event:
    - push

steps:
  - name: install
    image: node:12.16.2-alpine
    commands:
      - yarn

  - name: type-check
    image: node:12.16.2-alpine
    commands:
      - yarn type-check

  - name: lint
    image: node:12.16.2-alpine
    commands:
      - yarn lint
